list_one = ['comics', 'Spider-Man', 'Superman']
list_one.append('Darth Vader')
print(list_one)
list_two = list_one.copy()
print('list one: ')
print(list_one)
print('list two: ')
print(list_two)
print(list_one[3])
print(list_one.count('comics'))
list_one.insert(4, 'Green Lantern')
print(list_one)
list_one.remove('Green Lantern')
print(list_one)
list_one.reverse()
print(list_one)
list_one.sort()
print(list_one)
list_one.clear()
print(list_one)

